# SITE CONFIGURATION
baseurl: "" # the subpath of your site, e.g. /blog/
author: Benajmin Fehrensen, SCS
url: "http://m.swisscyberstorm.com" # the base hostname & protocol for your site

# News Title
NewsTitle: "Latest News"

# Hero Block -- typing on the start site 
heroImage: "hero.jpg"
heroTitle: "<typeout>"
eventDate: "October, 2016"
typeoutTextValues: '"Swiss Cyber Storm", "Swiss Cyber Storm 2016", "SCS 2016"'
typeoutFallback: "SCS 2016"

# THEME-SPECIFIC CONFIGURATION
theme:
  # Meta
  title: "Swiss Cyber Storm 2015 - International IT Security Conference"
  avatar: SCS_Logo.png
  gravatar: # email md5 hash
  description: "Swiss Cyber Storm 2015 Conference, European Cyber Security Challenge, Cyber Security Challenge, IT Security Conference Switzerland" # used by search engines
  

  # Header and footer text

  home_text: Home

  header_img: nodes_bg.jpg

  header_text: >
      <div>
      	<span id="mainTitle" class="fadeIn animated" style="font-size:80px;font-weight:bold;">Swiss Cyber Storm</span>
      	<img id="mainLogo" class="zoomIn animated" src="/img/SCS_Logo.png" alt="Swiss Cyber Storm Logo" width="100px" style="vertical-align:middle;margin-bottom:55px;">
      </div>
    
  call_out: >
      <a class="button-inverted" href="http://www.eventbee.com/v/swisscyberstorm/event?eid=128221942">
      Tickets / Registration
      </a>

  footer_text: >
    <div class="container">
      <div class="row">
        <div class="col-sm-6">
          &copy; 2016 Swiss Cyber Storm - Hosting provided by <a href="https://www.nine.ch/en/">nine.ch</a>
        </div>
      <div class="col-sm-6">
        <ul class="pull-right">
          <li><a href="/">Home</a></li>
          <li><a href="/about/committee">About Us</a></li>
          <li><a href="mailto:contact@swisscyberstorm.com">Contact Us</a></li>
        </ul>
      </div>
     </div>
    </div>
  
  # Icons
  rss: false
  email_address: # full email address, e.g. "sam@example.com"
  behance:
  bitbucket: 
  dribbble: 
  facebook: "SwissCyberStorm"
  flickr: 
  github:
  google_plus: 
  instagram: 
  linkedin:  # full URL
  pinterest: 
  reddit: 
  soundcloud: 
  stack_exchange:  # full URL
  steam: 
  tumblr: 
  twitter: "swisscyberstorm"
  wordpress: 
  youtube: 
  
  # Scripts
  google_analytics: # tracking id, e.g. "UA-000000-01"
  disqus_shortname:
  
  # Localization strings
  str_follow_on: "Follow on"
  str_rss_follow: "Follow RSS feed"
  str_email: "Email"
  str_next: "Next"
  str_prev: "Prev"
  str_continue_reading: "Continue reading"
  
  # Colors, typography and padding
  # Open the "_sass > base" folder, and open "_variables.scss"

# PAGINATION
paginate: 5
paginate_path: "/News/Blog/page:num"

# BUILD SETTINGS
markdown: kramdown
highlighter: pygments
sass:
  sass_dir: _sass
  style: :compressed


exclude: ['draft-program','README.md']
